# Numpy Array Dimensions

1D Array : Rows

2D Array : Rows and columns

3D Array : Matrice, Rows and Columns

In [2]:
import numpy as np     # importing numpy library

In [3]:
A = np.array(5)        # Scalar Array
A

array(5)

In [4]:
np.ndim(A)               # Dimension method

0

In [5]:
One = np.array([1, 2, 3, 4, 5]) # 1 d array single row # one d array one single opening and closing bracket

In [6]:
print(One)

[1 2 3 4 5]


In [7]:
np.ndim(One)

1

In [8]:
Two = np.array([[1, 2, 3], [4, 5, 6]]) # 2 d array rows and columns    # 2 opening and 2 closing brackets

In [9]:
print(Two)

[[1 2 3]
 [4 5 6]]


In [10]:
np.ndim(Two)

2

In [11]:
Three = np.array([[[1, 2, 3], [4, 5, 6]], # 3 d array matrice, rows, and columns
                 [[7, 8, 9], [10, 11, 12]]])

In [12]:
Three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
Three.shape
np.ndim(Three)

3

# List vs Numpy Array : computationally arrays are fatser than list.

In [14]:
list1 = [1,4.0,'apple']                     # List allows Different Datatypes
arr = np.array([1, 2, 3, 4, 5])             # Array allows Similar Datatypes

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
arr = np.array([1, 2, 3.9, 'apple'])        # Type Conversion

In [17]:
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [18]:
arr = np.array([1, 2, 3, 4, 5])             # Allows Mathematical Operations

arr/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
list1/5 # list cannot divide each element as it has different data types.

TypeError: unsupported operand type(s) for /: 'list' and 'int'

# More Advantages of Numpy Array over list

*   Array consumes less memory
*   Array are faster than lists



# Reshaping arrays

Reshaping means changing the shape of an array.

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

In [21]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array
newarr = arr.reshape(3, 4) # reshaping to 4 rowas and three columns


In [23]:
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
# 1D to 3D Array

newarr = arr.reshape(2, 3, 2)    # x,y,z: x = matrix, y = rows, z = cols


In [26]:
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [32]:
newarr = arr.reshape(4,3, 1)

In [33]:
print(newarr)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


# Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [35]:
arr = np.array([1, 2, 3, 4])              # Accessing 1D Array

print(arr[1])

2


In [37]:
print(arr[0] + arr[1])                 # Addition of 2 elements in an array using indexes

3


In [39]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  # Accessing 2D Array
arr.shape

(2, 5)

In [40]:
print(arr[0, 3])                          # 1st row 4th element

4


In [41]:
print(arr[0, 3])                          # 1st row 4th element

4


In [42]:
print(arr[1, 1])                          # 2nd row 5th element

7


In [43]:
print(arr[1,3])

9


In [44]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   # Accessing 3D Array

In [46]:
arr3.shape

(2, 2, 3)

In [47]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [48]:
print(arr3[0, 0, 2])               # 1st matrix, 1st row, 3rd column

3


In [49]:
print(arr3[1, 1, 1])               # 1st matrix, 2nd row, 1st column

11


In [50]:
print(arr3[0,1,0])

4


In [51]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
