## Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7])

In [3]:
print(a1[1:5])  # Slicing 1D Array

[2 3 4 5]


In [4]:
print(a1[4])     # Indexing

5


In [5]:
a1[:4]

array([1, 2, 3, 4])

In [6]:
a2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [7]:
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
a2[1, 1:4]

array([7, 8, 9])

In [9]:
a2[0:2, 2]

array([3, 8])

In [10]:
a2[1:, :5]

array([[ 6,  7,  8,  9, 10]])

In [11]:
a2.shape

(2, 5)

In [12]:
# a3.shape

In [13]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])           # # Slicing 3D Array

In [14]:
a3[:2,1:,:2]                                                          # [matrix:row:column]

array([[[13, 14],
        [16, 17]],

       [[23, 24],
        [26, 27]]])

In [15]:
a3[:2,1:,:]

array([[[13, 14, 15],
        [16, 17, 18]],

       [[23, 24, 25],
        [26, 27, 28]]])

In [16]:
a3[:2,1:,:2]

array([[[13, 14],
        [16, 17]],

       [[23, 24],
        [26, 27]]])

# View vs Copy

Copy is a new array, and the View is just a view of the original array.

Any changes made to the **copy** will not affect original array.

Any changes made to the **view** will affect the original array.

In [17]:
arr = np.array([1, 2, 3, 4, 5])

In [23]:
# Copy Method
copy = arr.copy()

In [24]:
copy[0] = 42

In [25]:
print(copy)

[42  2  3  4  5]


In [26]:
print(arr)

[1 2 3 4 5]


In [28]:
# View Method

view = arr.view()
view[0] = 42

print(arr)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]


# Append , Insert and Delete Operations

In [34]:
a = np.array([[1,2,3],
              [4,5,6]])  # Its a 2d array
a.shape

(2, 3)

In [35]:
# Append Method
np.append(a, [7,8,9]) # We are appending simple list

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.append(a, [[7,8,9]],axis = 0)                # axis = 0 = row , axis = 1 = col

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.append(a, [[5],[8]],axis = 1)

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [38]:
a = np.array([[1,2],
              [3,4],
              [5,6]])

# Insert Method

In [44]:
np.insert(a,3,[11,12])

array([ 1,  2,  3, 11, 12, 12,  9,  5,  6, 11,  8,  4, 10,  7])

In [40]:
np.insert(a,1,[11,12],axis = 0)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [41]:
np.insert(a,1,[11,12,13],axis = 1)

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 13,  6]])

In [45]:
a = np.array([[ 1,  2,  3, 12],
              [ 9,  5,  6,  11],
              [ 8,  4, 10, 7]])

# Delete Method

In [51]:
a = np.array([[ 1,  2,  3, 12],
              [ 9,  5,  6,  11],
              [ 8,  4, 10, 7]])

In [52]:
np.ndim(a)

2

In [53]:
np.delete(a,4)

array([ 1,  2,  3, 12,  5,  6, 11,  8,  4, 10,  7])

In [54]:
np.delete(a,1,axis = 1)

array([[ 1,  3, 12],
       [ 9,  6, 11],
       [ 8, 10,  7]])

In [55]:
np.delete(a,1,axis = 0)

array([[ 1,  2,  3, 12],
       [ 8,  4, 10,  7]])

# Hstack vs Vstack

Hstack is used to join two arrays **Horizontally**.

Vstack is used to join two arrays **Vertically**.


In [56]:
import numpy as np

In [57]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [58]:
print(a,b)
print(np.ndim(a), np.ndim(b))

[1 2 3] [4 5 6]
1 1


In [59]:
# Performing Hstack

result = np.hstack((a,b))

print(result)
print(np.ndim(result))

[1 2 3 4 5 6]
1


In [60]:
# Performing Vstack

result = np.vstack((a,b))

print(result, np.ndim(result))

[[1 2 3]
 [4 5 6]] 2


# Numpy Concatenation

It is used for joining two or more arrays of the same shape along a specified axis.

Axis = 0, Adding new rows

Axis = 1, Adding new columns


In [62]:
arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[3, 5], [7, 9]])

In [63]:
print(arr1.shape,arr2.shape)

(2, 2) (2, 2)


In [65]:
arr3 = np.array([[3], [9]])

arr4 = np.array([[4] , [8]])

In [67]:
print(arr3)

[[3]
 [9]]


In [68]:
print(arr4)

[[4]
 [8]]


In [66]:
print(arr3.shape,arr4.shape)

(2, 1) (2, 1)


In [69]:
new = np.concatenate((arr1, arr2), axis = 0)
print(new, new.shape)

[[2 4]
 [6 8]
 [3 5]
 [7 9]] (4, 2)


In [70]:
new = np.concatenate((arr3, arr4), axis = 1)
print(new)

[[3 4]
 [9 8]]
